const data ={
    products:[
        {
            _id:'1',
            name:'Fan Service',
            category:'service',
            image:'/images/service-1.jpg',
            price:120,
            countInStock:0,
            brand:'fixomech',
            rating:4.5,
            numReviews:10,
            description: 'high quaity product',
        },
        {
            _id:'2',
            name:'AC  Service',
            category:'service',
            image:'/images/service-1.jpg',
            price:120,
            countInStock:4,
            brand:'fixomech',
            rating:3,
            numReviews:10,
            description: 'high quaity product',
        },
        {
            _id:'3',
            name:'Washing Machine Service',
            category:'service',
            image:'/images/service-1.jpg',
            price:160,
            countInStock:6,
            brand:'fixomech',
            rating:4.5,
            numReviews:10,
            description: 'high quaity product',
        },
        {
            _id:'4',
            name:'TV Service',
            category:'service',
            image:'/images/service-1.jpg',
            price:150,
            countInStock:7,
            brand:'fixomech',
            rating:4.5,
            numReviews:10,
            description: 'high quaity product',
        },
        {
            _id:'5',
            name:'Wifi Service',
            category:'service',
            image:'/images/service-1.jpg',
            price:140,
            countInStock:0,
            brand:'fixomech',
            rating:4.5,
            numReviews:10,
            description: 'high quaity product',
        },
        {
            _id:'6',
            name:'Laptop Service',
            category:'service',
            image:'/images/service-1.jpg',
            price:140,
            countInStock:0,
            brand:'fixomech',
            rating:4.5,
            numReviews:10,
            description: 'high quaity product',
        }
    ]
}

export default data;